version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=gocart_db
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - gocart-network

  postgres:
    image: postgres:16-alpine
    container_name: gocart-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gocart_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gocart-network

volumes:
  postgres_data:

networks:
  gocart-network:
    driver: bridge 