name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: gocart_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Run tests with coverage
        working-directory: product-service
        run: go test -v ./... -coverprofile=coverage.out

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: product-service/coverage.out
          flags: unittests
          name: codecov-umbrella
