name: User Service Tests

on:
  push:
    branches:
      - main
    paths:
      - 'user-service/**'
      - 'internal/user-service/**'
      - 'pkg/**'
  pull_request:
    branches:
      - main
    paths:
      - 'user-service/**'
      - 'internal/user-service/**'
      - 'pkg/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: gocart_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod download

      - name: Run User Service tests
        working-directory: user-service
        run: go test -v ./... -coverprofile=coverage.out
        env:
          TEST_DB_HOST: localhost
          TEST_DB_USER: admin
          TEST_DB_PASSWORD: admin
          TEST_DB_NAME: gocart_db
          TEST_DB_PORT: 5432

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./user-service/coverage.out
          flags: user-service 